In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("sales_data.csv")

In [3]:
df.head(20)

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,...,Shipping Cost,Order Priority,Per unit sale price,Discount($),Per unit discount ($),cost price,per unit cost price,profit %,year,Month
0,0,42433,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,...,35.46,Medium,204.150,0.0000,0.00000,302.1600,151.0800,35.127085,2011,1
1,1,22253,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,9.72,Medium,40.122,12.0366,4.01220,84.3300,28.1100,42.732124,2011,1
2,2,48883,HU-2011-1220,2011-01-01,2011-05-01,Second Class,AT-735,Annie Thurman,Consumer,Budapest,...,8.17,High,16.530,0.0000,0.00000,36.4800,9.1200,81.250000,2011,1
3,3,11731,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,...,4.82,High,14.955,22.4325,7.47750,70.9200,23.6400,-36.738579,2011,1
4,4,22255,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,4.70,Medium,22.734,11.3670,2.27340,75.9000,15.1800,49.762846,2011,1
5,5,22254,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,1.80,Medium,27.621,5.5242,2.76210,39.9000,19.9500,38.451128,2011,1
6,6,21613,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,57.30,Critical,142.890,0.0000,0.00000,214.3800,107.1900,33.305346,2011,1
7,7,34662,CA-2011-115161,2011-01-02,2011-03-02,First Class,LC-17050,Liz Carlisle,Consumer,Mission Viejo,...,54.64,High,145.333,43.5999,21.79995,287.2464,143.6232,1.190476,2011,1
8,8,44508,AO-2011-1390,2011-01-02,2011-04-02,Second Class,DK-3150,David Kendrick,Corporate,Luanda,...,53.08,Critical,206.400,0.0000,0.00000,113.5200,113.5200,81.818182,2011,1
9,9,23688,ID-2011-56493,2011-01-02,2011-03-02,Second Class,SP-20650,Stephanie Phelps,Corporate,Yingcheng,...,44.36,Critical,54.240,0.0000,0.00000,94.4100,31.4700,72.354623,2011,1
10,10,25293,IN-2011-36074,2011-01-02,2011-05-02,Second Class,DK-13150,David Kendrick,Corporate,Chongqing,...,33.15,Medium,70.470,0.0000,0.00000,214.9500,42.9900,63.921842,2011,1
11,11,8483,US-2011-118892,2011-01-02,2011-06-02,Standard Class,DH-13075,Dave Hallsten,Corporate,San Miguelito,...,21.38,Medium,200.352,160.2816,80.14080,380.6800,190.3400,5.260061,2011,1
12,12,41445,IR-2011-6550,2011-01-02,2011-06-02,Standard Class,PO-8850,Patrick O'Brill,Consumer,Mashhad,...,19.65,High,51.600,0.0000,0.00000,161.1000,26.8500,92.178771,2011,1
13,13,16727,ES-2011-5268439,2011-01-02,2011-03-02,Second Class,GH-14485,Gene Hale,Corporate,La Rochelle,...,19.23,High,27.930,0.0000,0.00000,124.3500,24.8700,12.303981,2011,1
14,14,21615,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,11.13,Critical,13.560,0.0000,0.00000,28.8900,9.6300,40.809969,2011,1
15,15,8484,US-2011-118892,2011-01-02,2011-06-02,Standard Class,DH-13075,Dave Hallsten,Corporate,San Miguelito,...,6.21,Medium,40.992,32.7936,16.39680,101.1200,50.5600,-18.924051,2011,1
16,16,19796,ES-2011-5460465,2011-01-02,2011-05-02,Standard Class,RR-19315,Ralph Ritter,Consumer,Parma,...,6.03,Medium,26.100,0.0000,0.00000,57.9600,19.3200,35.093168,2011,1
17,17,21614,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,5.29,Critical,4.530,0.0000,0.00000,13.0500,2.6100,73.563218,2011,1
18,18,21616,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,3.78,Critical,6.780,0.0000,0.00000,10.4400,3.4800,94.827586,2011,1
19,19,16726,ES-2011-5268439,2011-01-02,2011-03-02,Second Class,GH-14485,Gene Hale,Corporate,La Rochelle,...,3.34,High,21.390,0.0000,0.00000,21.3900,21.3900,0.000000,2011,1

In [4]:
df.head(20)

,Unnamed: 0,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,...,Shipping Cost,Order Priority,Per unit sale price,Discount($),Per unit discount ($),cost price,per unit cost price,profit %,year,Month
0,0,42433,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,...,35.46,Medium,204.150,0.0000,0.00000,302.1600,151.0800,35.127085,2011,1
1,1,22253,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,9.72,Medium,40.122,12.0366,4.01220,84.3300,28.1100,42.732124,2011,1
2,2,48883,HU-2011-1220,2011-01-01,2011-05-01,Second Class,AT-735,Annie Thurman,Consumer,Budapest,...,8.17,High,16.530,0.0000,0.00000,36.4800,9.1200,81.250000,2011,1
3,3,11731,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,...,4.82,High,14.955,22.4325,7.47750,70.9200,23.6400,-36.738579,2011,1
4,4,22255,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,4.70,Medium,22.734,11.3670,2.27340,75.9000,15.1800,49.762846,2011,1
5,5,22254,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,1.80,Medium,27.621,5.5242,2.76210,39.9000,19.9500,38.451128,2011,1
6,6,21613,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,57.30,Critical,142.890,0.0000,0.00000,214.3800,107.1900,33.305346,2011,1
7,7,34662,CA-2011-115161,2011-01-02,2011-03-02,First Class,LC-17050,Liz Carlisle,Consumer,Mission Viejo,...,54.64,High,145.333,43.5999,21.79995,287.2464,143.6232,1.190476,2011,1
8,8,44508,AO-2011-1390,2011-01-02,2011-04-02,Second Class,DK-3150,David Kendrick,Corporate,Luanda,...,53.08,Critical,206.400,0.0000,0.00000,113.5200,113.5200,81.818182,2011,1
9,9,23688,ID-2011-56493,2011-01-02,2011-03-02,Second Class,SP-20650,Stephanie Phelps,Corporate,Yingcheng,...,44.36,Critical,54.240,0.0000,0.00000,94.4100,31.4700,72.354623,2011,1
10,10,25293,IN-2011-36074,2011-01-02,2011-05-02,Second Class,DK-13150,David Kendrick,Corporate,Chongqing,...,33.15,Medium,70.470,0.0000,0.00000,214.9500,42.9900,63.921842,2011,1
11,11,8483,US-2011-118892,2011-01-02,2011-06-02,Standard Class,DH-13075,Dave Hallsten,Corporate,San Miguelito,...,21.38,Medium,200.352,160.2816,80.14080,380.6800,190.3400,5.260061,2011,1
12,12,41445,IR-2011-6550,2011-01-02,2011-06-02,Standard Class,PO-8850,Patrick O'Brill,Consumer,Mashhad,...,19.65,High,51.600,0.0000,0.00000,161.1000,26.8500,92.178771,2011,1
13,13,16727,ES-2011-5268439,2011-01-02,2011-03-02,Second Class,GH-14485,Gene Hale,Corporate,La Rochelle,...,19.23,High,27.930,0.0000,0.00000,124.3500,24.8700,12.303981,2011,1
14,14,21615,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,11.13,Critical,13.560,0.0000,0.00000,28.8900,9.6300,40.809969,2011,1
15,15,8484,US-2011-118892,2011-01-02,2011-06-02,Standard Class,DH-13075,Dave Hallsten,Corporate,San Miguelito,...,6.21,Medium,40.992,32.7936,16.39680,101.1200,50.5600,-18.924051,2011,1
16,16,19796,ES-2011-5460465,2011-01-02,2011-05-02,Standard Class,RR-19315,Ralph Ritter,Consumer,Parma,...,6.03,Medium,26.100,0.0000,0.00000,57.9600,19.3200,35.093168,2011,1
17,17,21614,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,5.29,Critical,4.530,0.0000,0.00000,13.0500,2.6100,73.563218,2011,1
18,18,21616,IN-2011-30733,2011-01-02,2011-03-02,Second Class,PO-18865,Patrick O'Donnell,Consumer,Dhaka,...,3.78,Critical,6.780,0.0000,0.00000,10.4400,3.4800,94.827586,2011,1
19,19,16726,ES-2011-5268439,2011-01-02,2011-03-02,Second Class,GH-14485,Gene Hale,Corporate,La Rochelle,...,3.34,High,21.390,0.0000,0.00000,21.3900,21.3900,0.000000,2011,1

In [5]:
df.to_json("sales.js")

In [6]:
columns=df.columns
columns

Index(['Unnamed: 0', 'Row ID', 'Order ID', 'Order Date', 'Ship Date',
       'Ship Mode', 'Customer ID', 'Customer Name', 'Segment', 'City', 'State',
       'Country', 'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority', 'Per unit sale price',
       'Discount($)', 'Per unit discount ($)', 'cost price',
       'per unit cost price', 'profit %', 'year', 'Month'],
      dtype='object')

In [7]:
sql_df =df.rename({'Row ID': 'Row_ID', 'Order ID': 'Order_ID','Order Date':'Order_Date','Ship Date':'Ship_Date',
                   'Ship Mode':'Ship_Mode','Customer ID':'Customer_ID','Customer Name':'Customer_Name','State':'States',
                   'Postal Code':'Postal_Code','Product ID':'Product_ID','Sub-Category':'Sub_Category',
                   'Product Name':'Product_Name','Shipping Cost':'Shipping_Cost','Order Priority':'Order_Priority',
                   'Per unit sale price':'Per_unit_sale_price','Discount($)':'Discount_dollars',
                   'Per unit discount ($)':'Per_unit_discount_dollars','cost price':'cost_price',
                   'per unit cost price':'per_unit_cost_price',
                   'profit %':'profit_percentage','year':'years','Month':'Months'}, axis='columns')

In [8]:
sql_df.head()

,Unnamed: 0,Row_ID,Order_ID,Order_Date,Ship_Date,Ship_Mode,Customer_ID,Customer_Name,Segment,City,...,Shipping_Cost,Order_Priority,Per_unit_sale_price,Discount_dollars,Per_unit_discount_dollars,cost_price,per_unit_cost_price,profit_percentage,years,Months
0,0,42433,AG-2011-2040,2011-01-01,2011-06-01,Standard Class,TB-11280,Toby Braunhardt,Consumer,Constantine,...,35.46,Medium,204.150,0.0000,0.0000,302.16,151.08,35.127085,2011,1
1,1,22253,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,9.72,Medium,40.122,12.0366,4.0122,84.33,28.11,42.732124,2011,1
2,2,48883,HU-2011-1220,2011-01-01,2011-05-01,Second Class,AT-735,Annie Thurman,Consumer,Budapest,...,8.17,High,16.530,0.0000,0.0000,36.48,9.12,81.250000,2011,1
3,3,11731,IT-2011-3647632,2011-01-01,2011-05-01,Second Class,EM-14140,Eugene Moren,Home Office,Stockholm,...,4.82,High,14.955,22.4325,7.4775,70.92,23.64,-36.738579,2011,1
4,4,22255,IN-2011-47883,2011-01-01,2011-08-01,Standard Class,JH-15985,Joseph Holt,Consumer,Wagga Wagga,...,4.70,Medium,22.734,11.3670,2.2734,75.90,15.18,49.762846,2011,1

In [9]:
sql_df.columns

Index(['Unnamed: 0', 'Row_ID', 'Order_ID', 'Order_Date', 'Ship_Date',
       'Ship_Mode', 'Customer_ID', 'Customer_Name', 'Segment', 'City',
       'States', 'Country', 'Postal_Code', 'Market', 'Region', 'Product_ID',
       'Category', 'Sub_Category', 'Product_Name', 'Sales', 'Quantity',
       'Discount', 'Profit', 'Shipping_Cost', 'Order_Priority',
       'Per_unit_sale_price', 'Discount_dollars', 'Per_unit_discount_dollars',
       'cost_price', 'per_unit_cost_price', 'profit_percentage', 'years',
       'Months'],
      dtype='object')

In [45]:
# customer table
Customer=sql_df[["Row_ID","Customer_ID","Customer_Name","Segment"]]
Customer.head()
Customer.to_csv("Customer.csv")

In [42]:
#sales table
Sales=sql_df[["Row_ID","Sales","Quantity","Profit","cost_price","Months","years"]]
Sales.head()
Sales.to_csv("sales.csv")

In [44]:
#Shipping_info

Shipping_info=sql_df[["Order_ID","Row_ID","City","States","Country","Shipping_Cost",'Order_Priority',"Ship_Mode","Market","Region"]]
Shipping_info.head()
Shipping_info.to_csv("Shipping_info.csv")

In [46]:
#Product table
Product=sql_df[["Row_ID","Order_ID","Product_ID","Category","Sub_Category","Segment"]]
Product.head()
Product.to_csv("Product.csv")